= Pykrete Whitebox

Implementation of AES whitebox schemes Chow and Karroumi (both one dual per round and one dual per row per round) in pure Rust.

== Implementation details

Some things here are transposed compared to standard AES implementation, this transposition is performed because of the
poorly drawn designs in my research notes, lol. I would like to rename everything properly, but then the code won't
align with my drawings, and I'm only be able to reason about the code using them.

== Performance

Similar to other whitebox aes implementations during runtime, but the compiler is very slow.

I have not used any library for matrix math (because there I have found no good GF2 math libraries for Rust),
many calculations (especially matrix inversions) are performed on the spot instead of caching them/passing them around,
and because of that this project is pretty CPU hungry, especially for Karroumi impl, as it compuates sbox multiple times
for every single round.

== Security

What security?

Do not use this if you don't know what are you doing. Better - do not use this at all other than for learning purposes.

Not included in this repo many improvements over karroumi scheme, more security measures, and analyzer that is able to
reverse the VM code (as generated by published mkvm codegenerator) using DFA, meaning you can consider this
implementation as compromised as every other whitebox aes implementation.

There is multiple ways this implementation might be improved, but I only want this repo to be AES/Rjindael adjacement
with the algorighms primarily based on academic papers.

== License

GPLv3 with me (Lach) solely holding the copyright. I have a proprietary version of the same codebase with private
modification that is being used for some other tasks.

== Credits

Dušan Klinec: White-box attack resistant cryptography.

Stanley Chow, Phil Eisen, Harold Johnson, and Paul C. Van Oorschot: White-box cryptography and an AES implementation.

Mohamed Karroumi: Protecting white-box AES with dual ciphers.

